<?php
/**
 * Страница "Разметка фрагмента шаблона".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Template block markup</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/markupblock.png' ?>" />
    </div>
    <p>Block marking is the indication of the area (block) of the template of the corresponding signature.</p>
    <p>Markup is used to edit a specific, most frequently used area of the template, for example: "Contacts", "Slogan", etc.</p>
</article>