<?php
/**
 * Страница "Панель инструментов Визуального редактора".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Visual editor panel tools</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/panel.png' ?>" />
    </div>
    <p>The default panel is positioned vertically on the screen along the left edge of the Visual editor.</p>
    <h2>Panel tools</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-lighton.svg' ?>" /> <b>Enable page markup.</b> Enables (icon highlight) or disables (icon not highlighted) the markup of all components on the page. The markup shows the component's boundaries and provides control over it;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-refresh.svg' ?>" /> <b>Page refresh.</b> Allows you to refresh the page in case of any error or if the page is not loaded correctly;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-back.svg' ?>" />  <img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-forward.svg' ?>" /> <b>Jump between pages.</b> «Back» - allows you to return to the previous page that was recently viewed. «Forward» - is used to go to the next page that was recently viewed;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-article.svg' ?>" /> <b>Editing an article.</b> Performs editing of the article if it is on the page;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-acategory.svg' ?>" /> <b>Editing an article category (section).</b> Edits the category of the article if it is on the page;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-seo.svg' ?>" /> <b>Search engine optimization.</b> Shows a list of components that are used for search engine optimization;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-components.svg' ?>" /> <b>Components of the current page.</b> Contains a drop-down list of components of the current page. Allows you to quickly go to the component settings or edit its data;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-blocks.svg' ?>" /> <b>Fragments of the current page.</b> Allows you to edit the site fragment template by selecting it from the drop-down menu. The button is not available if there are no fragments on the page;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-blank.svg' ?>" /> <b>Opening a page in a new browser tab.</b> Opening a page in a new browser tab;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-help.svg' ?>" /> <b>Help.</b> Shows the help information window..</li>
    </ul>
</article>